### ISSUE TITLE
Request for Review: DF Scene Enhancement

### ISSUE THREAD

**Issue by flamewave000** [bryancasler/Bryans-Preferred-Modules-for-FoundryVTT#3]
The QuickSceneView module is outdated and hasn't been updated for 0.7.x, I built a module that has that view feature but on clicking the card instead of in the menu, and a few more features that are very useful.

- Navigate to scene instead of displaying config when clicking a scene on the Scenes Tab.
- Display dialog with Config, Journal, and Navigate options when clicking a scene link in a Journal Entry.
- Set custom Thumbnail for a scene.
- Allow players to see the Scenes Tab with the scenes they have access to.

[DF Scene Enhancement](https://foundryvtt.com/packages/df-scene-enhance/)

**Comment by bryancasler** [comment]
Hi @flamewave000 thank you so much for jumping in to let me know about your module. Can't wait to try it out, sounds like some nice and intuitive usability improvements.

**Comment by bryancasler** [comment]
This repo is no longer maintained, going to close this out.
